# Site settings
title: Master Calcul Scientifique et Mathématiques de l'Information
email: contact-csmi@cemosis.fr
description: 
baseurl: 
url: "http://csmi.cemosis.fr/"
twitter_username: 
github_username: 

# Build settings
markdown: kramdown

languages: ["fr", "en", "de"]

exclude_from_localizations: ["js", "images", "stylesheet"]
